{
 "title": "Time-to-Click Comparison",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average Time to Click – Main",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(time_to_click_seconds_sum{destination_app=\"app\"}[1m]) / rate(time_to_click_seconds_count{destination_app=\"app\"}[1m])"
    }
   ]
  },
  {
   "title": "Average Time to Click – Canary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(time_to_click_seconds_sum{destination_app=\"app-v1\"}[1m]) / rate(time_to_click_seconds_count{destination_app=\"app-v2\"}[1m])"
    }
   ]
  },
  {
   "title": "Time-to-Click Distribution",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(time_to_click_seconds_bucket{destination_app=~\"app|app-canary\"}[1m])) by (le, destination_app))",
     "legendFormat": "P50 – {{destination_app}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(time_to_click_seconds_bucket{destination_app=~\"app|app-canary\"}[1m])) by (le, destination_app))",
     "legendFormat": "P90 – {{destination_app}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(time_to_click_seconds_bucket{destination_app=~\"app|app-canary\"}[1m])) by (le, destination_app))",
     "legendFormat": "P99 – {{destination_app}}"
    }
   ]
  }
 ]
}