version: latest #latest one I believe

services:
  #First service hosts the ML model through REST
  model-service:
    image: ${MODEL_IMAGE:-ghcr.io/remla25-team4/model-service:latest}
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    secrets:
      - model-secret

  #This contains the frontend and backend of the app   
  app:
    image: ${APP_IMAGE:-ghcr.io/remla25-team4/app:latest}
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - .env
    depends_on:
      - model-service

secrets:
  model-secret:
    file: ./secrets/model-api-key.txt

    
