version: latest #latest one I believe

services:
  #First service hosts the ML model through REST
  model-service:
    image: ${MODEL_IMAGE:-ghcr.io/remla25-team4/model-service:latest}
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env

  #This contains the frontend and backend of the app   
  app:
    image: ${MODEL_IMAGE:-ghcr.io/remla25-team4/model-service:latest}
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - .env
    depends_on:
      - model-service
    
