- hosts: all
  become: true
  tasks: 
  - name: Add SSH key
    ansible.posix.authorized_key:
      user: vagrant
      state: present
      key: '{{ item }}'
    with_file:
      - public-keys/alexgliga
      - public-keys/alexpostu
