- hosts: all
  become: true
  tasks:
    - name: Get kubeadm join command from our controller
      shell: kubeadm token create --print-join-command
      delegate_to: ctrl
      register: join_command
      run_once: true
    - name: Join the node to the cluster
      ansible.builtin.shell: "{{ join_command.stdout }}"
