{
 "title": "Time to Click Comparison",
 "refresh": "10s",
 "panels": [
  {
   "title": "Average Time to Click - Main",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(time_to_click_seconds_sum{version=\"main\"}[1m]) / rate(time_to_click_seconds_count{version=\"main\"}[1m])"
    }
   ]
  },
  {
   "title": "Average Time to Click - Canary",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(time_to_click_seconds_sum{version=\"canary\"}[1m]) / rate(time_to_click_seconds_count{version=\"canary\"}[1m])"
    }
   ]
  },
  {
   "title": "Time to Click Distribution",
   "type": "barchart",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(time_to_click_seconds_bucket[1m])) by (le, version))",
     "legendFormat": "P50 - {{version}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(time_to_click_seconds_bucket[1m])) by (le, version))",
     "legendFormat": "P90 - {{version}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(time_to_click_seconds_bucket[1m])) by (le, version))",
     "legendFormat": "P99 - {{version}}"
    }
   ]
  }
 ]
}