{
 "title": "Restaurant sentiment dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Failed prediction requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "failed_prediction_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wrong predictions counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "wrong_prediction_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Currently active prediction requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    { "expr": "active_prediction_requests", "legendFormat": "__auto" }
   ]
  }
 ]
}