app:
  name: app
  image: ghcr.io/remla25-team4/app
  tag: "latest"
  port: 3001
  env:
    MODEL_SERVICE_URL: "http://model-service:8080"

model:
  name: model-service
  image: ghcr.io/remla25-team4/model-service
  tag: "latest"
  port: 8080
  env:
    MODEL_URL: "https://github.com/remla25-team4/model-training/raw/main/models/naive_bayes.joblib"

  
fullnameOverride: restaurant-sentiment

#config:
  
#secret:
#  smtp_password: ""
