{{/* operations/restaurant-sentiment/templates/app-ingress.yaml */}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "restaurant-sentiment.app.fullname" . }}-ingress
  labels:
    {{- include "restaurant-sentiment.labels" . | nindent 4 }}
    app.kubernetes.io/component: app-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "restaurant-sentiment.app.fullname" . }}
                port:
                  name: http
{{- end }}
