{{/* operations/restaurant-sentiment/templates/app-svc.yaml */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "restaurant-sentiment.app.fullname" . }}
  labels:
    {{- include "restaurant-sentiment.labels" . | nindent 4 }}
    {{- include "restaurant-sentiment.selectorLabels" (dict "root" . "component" "app") | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "restaurant-sentiment.selectorLabels" (dict "root" . "component" "app") | nindent 4 }}