{{/* operations/restaurant-sentiment/templates/app-secret.yaml */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restaurant-sentiment.app.fullname" . }}-secret
  labels:
    {{- include "restaurant-sentiment.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
type: Opaque
data:
  # using dummy values from values.yaml, base64 encoded.
  {{- range $key, $value := .Values.app.secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
