prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.local

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.local
      
  adminUser: admin
  adminPassword: admin