{
 "title": "Restaurant sentiment dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Wrong Predictions per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(wrong_prediction_counter_total[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (predicted_sentiment)(increase(wrong_prediction_counter_total[$__rate_interval]))",
     "legendFormat": "{{predicted_sentiment}}"
    }
   ]
  },
  {
   "title": "Avg Nr. Positive Reviews",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(total_prediction_requests_total{sentiment=\"positive\"})"
    }
   ]
  },
  {
   "title": "Active Prediction Requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_prediction_requests" }
   ]
  },
  {
   "title": "Failed Review Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (error_type) (increase(failed_prediction_requests_total[$__rate_interval]))",
     "legendFormat": "{{error_type}}"
    }
   ]
  }
 ]
}