apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.server.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.server.evaluationInterval }}

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'restaurant-app'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['restaurant-sentiment-app:3001']

      - job_name: 'model-service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['restaurant-sentiment-model-svc:8080'] 

