apiVersion: v1
kind: Pod
metadata:
  name: app-v1
  labels: { app: app, version: v1 }
spec:
  containers:
  - name: app
    image: ghcr.io/remla25-team4/app:latest
    ports: [ containerPort: 3001 ]
---
apiVersion: v1
kind: Pod
metadata:
  name: svc-v1
  labels: { app: svc, version: v1 }
spec:
  containers:
  - name: svc
    image: ghcr.io/remla25-team4/model-service:latest
    ports: [ containerPort: 8080 ]
    env:
    - { MODEL_URL: "https://github.com/remla25-team4/model-training/raw/main/models/naive_bayes.joblib" }
---
apiVersion: v1
kind: Service
metadata: { name: app }
spec:
  selector: { app: app }
  ports:
  - { name: http, port: 1234, targetPort: 3001 }
---
apiVersion: v1
kind: Service
metadata: { name: svc }
spec:
  selector: { app: svc }
  ports:
  - { name: http, port: 1234, targetPort: 8080 }
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata: { name: my-gateway }
spec:
  selector: { istio: ingressgateway }
  servers:
  - port: { number: 80, name: http, protocol: HTTP }
  hosts: [ "*" ]